#!/bin/bash
if [ ! -e /fastsubtrees/example-app-initialized ]; then
  # doing this allows to avoid re-creating the tree data
  # if it was already done before, e.g. for the benchmarks or ntsubtree
  create-tree-file
  cd /fastsubtrees/genomes_attributes_viewer/ && pip install -e .
  touch /fastsubtrees/example-app-initialized
fi
genomes-attributes-viewer
